### after ros_gl
FROM @NAME_SPACE@/ros_gl:@UBUNTU_VERSION@

## WORKDIR /userdir

SHELL ["/bin/bash", "-c"]

ENV CNOID_PARENT_SETUP /opt/ros/$ROS_DISTRO/setup.bash

RUN apt-get update -q -qq && apt-get install -q -qq -y \
    mesa-utils python-pip \
    ros-${ROS_DISTRO}-catkin python-wstools python-catkin-tools \
# choreonoid
    libyaml-dev ros-kinetic-openrtm-aist ros-kinetic-openrtm-aist-python libqt4-opengl-dev python3-yaml \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

### install choreonoid
ENV CNOID_BRANCH @CHOREONOID_VERSION@

## choreonoid
WORKDIR /choreonoid_ws

RUN wstool init src && \
#    (cd src; git clone --depth 1 -b ${CNOID_BRANCH} https://github.com/s-nakaoka/choreonoid.git choreonoid) && \
    (cd src; git clone --depth 1 -b ${CNOID_BRANCH} https://github.com/YoheiKakiuchi/choreonoid.git choreonoid) && \
#    wstool set -y -t src choreonoid_rosplugin       https://github.com/s-nakaoka/choreonoid_rosplugin.git --git && \
    wstool set -y -t src choreonoid_rosplugin       https://github.com/YoheiKakiuchi/choreonoid_rosplugin.git -v latest_for_agentsystem2019 --git && \
#    wstool set -y -t src choreonoid_ros_samples     https://github.com/s-nakaoka/choreonoid_ros_samples.git --git && \
    wstool set -y -t src choreonoid_ros_samples     https://github.com/YoheiKakiuchi/choreonoid_ros_samples.git -v latest_for_agentsystem2019 --git && \
#    wstool set -y -t src choreonoid_joy             https://github.com/s-nakaoka/choreonoid_joy.git --git && \
    wstool set -y -t src choreonoid_joy             https://github.com/YoheiKakiuchi/choreonoid_joy.git -v latest_for_agentsystem2019 --git && \
    wstool set -y -t src aizuspider_description     https://github.com/agent-system/aizuspider_description.git --git && \
    wstool update -t src && \
    sed -i -e 's@OPENRTM_VERSION STREQUAL "1.1.2"@OPENRTM_VERSION STREQUAL "1.1.0"@' src/choreonoid/CMakeLists.txt && \
    sed -i -e 's@OPENRTM_VERSION VERSION_EQUAL "1.1.2"@OPENRTM_VERSION VERSION_EQUAL "1.1.0"@' src/choreonoid/CMakeLists.txt && \    
    sed -i -e 's@sudo apt-get -y install@apt-get install -q -qq -y@' src/choreonoid/misc/script/install-requisites-ubuntu-16.04.sh && \
    apt-get update -q -qq && \
    rosdep install -q -y -r --from-paths src --ignore-src || echo 'Ignore rosdep error' && \
    src/choreonoid/misc/script/install-requisites-ubuntu-16.04.sh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /choreonoid_ws

RUN source ${CNOID_PARENT_SETUP} && \
    catkin build choreonoid -DENABLE_CORBA=ON -DBUILD_CORBA_PLUGIN=ON -DBUILD_OPENRTM_PLUGIN=ON -DBUILD_HELLO_WORLD_SAMPLE=ON -DBUILD_SPRING_MODEL_SAMPLE=ON -DUSE_BUILTIN_CAMERA_IMAGE_IDL=ON -DBUILD_WRS2018=ON @EXTRA_CNOID_CMAKE_OPTIONS@
    
RUN source ${CNOID_PARENT_SETUP} && \
    if [ -e /choreonoid_ws/src/choreonoid/thirdparty/pybind11-2.2.4/include/pybind11 ]; then ln -sf /choreonoid_ws/src/choreonoid/thirdparty/pybind11-2.2.4/include/pybind11 devel/include/choreonoid-1.7; fi && \
    catkin build            -DENABLE_CORBA=ON -DBUILD_CORBA_PLUGIN=ON -DBUILD_OPENRTM_PLUGIN=ON -DBUILD_HELLO_WORLD_SAMPLE=ON -DBUILD_SPRING_MODEL_SAMPLE=ON -DUSE_BUILTIN_CAMERA_IMAGE_IDL=ON -DBUILD_WRS2018=ON @EXTRA_CNOID_CMAKE_OPTIONS@ && \
    catkin clean -b -l -y

###
ADD ./my_entrypoint.sh /
ADD ./my_entryrc /
ENTRYPOINT ["/my_entrypoint.sh"]
CMD ["bash"]
