### after ros_gl
FROM yoheikakiuchi/ros_gl:@UBUNTU_VERSION@

## WORKDIR /userdir

SHELL ["/bin/bash", "-c"]

RUN apt-get update -q -qq && apt-get install -q -qq -y \
    mesa-utils python-pip \
    ros-${ROS_DISTRO}-catkin python-wstools python-catkin-tools \
# choreonoid
    libyaml-dev ros-kinetic-openrtm-aist ros-kinetic-openrtm-aist-python libqt4-opengl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

### install choreonoid
ENV CNOID_BRANCH master

ENV CNOID_INSTALL_DIR /usr/local/choreonoid
ENV PATH ${CNOID_INSTALL_DIR}/bin:${PATH}
ENV LD_LIBRARY_PATH ${CNOID_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}
ENV PKG_CONFIG_PATH ${CNOID_INSTALL_DIR}/lib/pkgconfig:${PKG_CONFIG_PATH}
ENV CNOID_RTM_DIR /opt/ros/${ROS_DISTRO}

## choreonoid
WORKDIR /tmp
RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    git clone --depth 1 -b ${CNOID_BRANCH} https://github.com/s-nakaoka/choreonoid.git choreonoid && \
    echo -e 'diff --git choreonoid/CMakeLists.txt choreonoid/CMakeLists.txt\n\
index d290f66..6a8588a 100644\n\
--- choreonoid/CMakeLists.txt\n\
+++ choreonoid/CMakeLists.txt\n\
@@ -920,7 +920,7 @@ if(BUILD_OPENRTM_PLUGIN)\n\
   set(IDL_INCLUDE_DIRS ${IDL_INCLUDE_DIRS} ${OPENRTM_INCLUDE_DIRS})\n\
 \n   # Check version\n\
-  if(OPENRTM_VERSION STREQUAL "1.1.2")\n\
+  if(OPENRTM_VERSION STREQUAL "1.1.0")\n\
     list(APPEND OPENRTM_DEFINITIONS -DOPENRTM_VERSION11)\n\
   elseif(OPENRTM_VERSION STREQUAL "1.2.0")\n\
     list(APPEND OPENRTM_DEFINITIONS -DOPENRTM_VERSION12)' | patch -p0 && \
    mkdir -p choreonoid/build && \
    cd choreonoid/build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=${CNOID_INSTALL_DIR} -DOPENRTM_DIR=${CNOID_RTM_DIR} -DENABLE_INSTALL_RPATH=ON -DENABLE_CORBA=ON -DBUILD_CORBA_PLUGIN=ON -DBUILD_OPENRTM_PLUGIN=ON -DBUILD_HELLO_WORLD_SAMPLE=ON -DBUILD_SPRING_MODEL_SAMPLE=ON -DUSE_PYTHON3=OFF -DUSE_PYBIND11=OFF -DUSE_BUILTIN_CAMERA_IMAGE_IDL=ON && \
    make -j4 && \
    make install && \
    rm -rf choreonoid
