### after ros_gl
FROM @NAME_SPACE@/ros_gl:@UBUNTU_VERSION@

## WORKDIR /userdir

SHELL ["/bin/bash", "-c"]

RUN apt-get update -q -qq && apt-get install -q -qq -y \
    mesa-utils python-pip \
    ros-${ROS_DISTRO}-catkin python-wstools python-catkin-tools \
# choreonoid
    libyaml-dev ros-kinetic-openrtm-aist ros-kinetic-openrtm-aist-python libqt4-opengl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

### install choreonoid
ENV CNOID_BRANCH @CHOREONOID_VERSION@

ENV CNOID_INSTALL_DIR /usr/local/choreonoid
ENV PATH ${CNOID_INSTALL_DIR}/bin:${PATH}
ENV LD_LIBRARY_PATH ${CNOID_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}
ENV PKG_CONFIG_PATH ${CNOID_INSTALL_DIR}/lib/pkgconfig:${PKG_CONFIG_PATH}
ENV CNOID_RTM_DIR /opt/ros/${ROS_DISTRO}

## choreonoid
WORKDIR /tmp
RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    git clone --depth 1 -b ${CNOID_BRANCH} https://github.com/s-nakaoka/choreonoid.git choreonoid && \
    mkdir -p choreonoid/build && \
    cd choreonoid/build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=${CNOID_INSTALL_DIR} -DOPENRTM_DIR=${CNOID_RTM_DIR} -DENABLE_INSTALL_RPATH=ON -DENABLE_CORBA=ON -DBUILD_CORBA_PLUGIN=ON -DBUILD_OPENRTM_PLUGIN=ON -DBUILD_HELLO_WORLD_SAMPLE=ON -DBUILD_SPRING_MODEL_SAMPLE=ON -DUSE_PYTHON3=OFF -DUSE_PYBIND11=OFF -DUSE_BUILTIN_CAMERA_IMAGE_IDL=ON -DBUILD_WRS2018=ON && \
    make -j4 && \
    make install && \
    rm -rf choreonoid

###
ADD ./my_entrypoint.sh /
ADD ./my_entryrc /
ENTRYPOINT ["/my_entrypoint.sh"]
CMD ["bash"]
